variable "linode_token" {}
variable "linode_instance_image" {}
variable "linode_instance_type" {}
variable "linode_instance_tags" {}
variable "linode_instance_root_pass" {}
variable "linode_instance_label" {}
variable "linode_instance_region" {}
variable "linode_virtualserver_firewall_label" {}
variable "linode_build_image_label" {}
variable "linode_security_script_label" {}
variable "linode_apm_script_label" {}
variable "linode_apm_sec_script_label" {}
variable "build_image_type" {}
